version: '3.8'

networks:
  my-network:
    driver: bridge


services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_DB: SkillShare
    ports:
      - "5431:5432"
    networks:
      - my-network

  app:
    image: skill-share:latest
    build: ./main-service
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: pre-prod
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/SkillShare
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: qwerty1234
    networks:
      - my-network
    depends_on:
      - postgres
