version: '3.8'

networks:
  my-network:
    driver: bridge


services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_DB: SkillShare
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  app:
    build: ./main-service
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/SkillShare
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: qwerty1234
    networks:
      - my-network
    depends_on:
      - postgres

volumes:
  postgres-data:
