/*
 * This file is generated by jOOQ.
 */
package ru.skillaurora.profileservice.model.jooq.schema.tables.records;


import java.time.LocalDate;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.skillaurora.profileservice.model.jooq.schema.tables.ProfileInfo;
import ru.skillaurora.profileservice.model.jooq.schema.tables.pojos.ProfileInfoEntity;


/**
 * Таблица данных профиля пользователя
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileInfoRecord extends UpdatableRecordImpl<ProfileInfoRecord> implements Record9<UUID, String, String, String, String, Short, Long, LocalDate, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.profile_info.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.profile_info.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.profile_info.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.profile_info.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.profile_info.real_name</code>.
     */
    public void setRealName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.profile_info.real_name</code>.
     */
    public String getRealName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.profile_info.about_me</code>.
     */
    public void setAboutMe(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.profile_info.about_me</code>.
     */
    public String getAboutMe() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.profile_info.profile_picture</code>.
     */
    public void setProfilePicture(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.profile_info.profile_picture</code>.
     */
    public String getProfilePicture() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.profile_info.country_id</code>.
     */
    public void setCountryId(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.profile_info.country_id</code>.
     */
    public Short getCountryId() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.profile_info.rating</code>.
     */
    public void setRating(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.profile_info.rating</code>.
     */
    public Long getRating() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.profile_info.register_date</code>.
     */
    public void setRegisterDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.profile_info.register_date</code>.
     */
    public LocalDate getRegisterDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>public.profile_info.account_status</code>.
     */
    public void setAccountStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.profile_info.account_status</code>.
     */
    public String getAccountStatus() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, String, String, String, String, Short, Long, LocalDate, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, String, String, String, String, Short, Long, LocalDate, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ProfileInfo.PROFILE_INFO_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return ProfileInfo.PROFILE_INFO_ENTITY.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return ProfileInfo.PROFILE_INFO_ENTITY.REAL_NAME;
    }

    @Override
    public Field<String> field4() {
        return ProfileInfo.PROFILE_INFO_ENTITY.ABOUT_ME;
    }

    @Override
    public Field<String> field5() {
        return ProfileInfo.PROFILE_INFO_ENTITY.PROFILE_PICTURE;
    }

    @Override
    public Field<Short> field6() {
        return ProfileInfo.PROFILE_INFO_ENTITY.COUNTRY_ID;
    }

    @Override
    public Field<Long> field7() {
        return ProfileInfo.PROFILE_INFO_ENTITY.RATING;
    }

    @Override
    public Field<LocalDate> field8() {
        return ProfileInfo.PROFILE_INFO_ENTITY.REGISTER_DATE;
    }

    @Override
    public Field<String> field9() {
        return ProfileInfo.PROFILE_INFO_ENTITY.ACCOUNT_STATUS;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getRealName();
    }

    @Override
    public String component4() {
        return getAboutMe();
    }

    @Override
    public String component5() {
        return getProfilePicture();
    }

    @Override
    public Short component6() {
        return getCountryId();
    }

    @Override
    public Long component7() {
        return getRating();
    }

    @Override
    public LocalDate component8() {
        return getRegisterDate();
    }

    @Override
    public String component9() {
        return getAccountStatus();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getRealName();
    }

    @Override
    public String value4() {
        return getAboutMe();
    }

    @Override
    public String value5() {
        return getProfilePicture();
    }

    @Override
    public Short value6() {
        return getCountryId();
    }

    @Override
    public Long value7() {
        return getRating();
    }

    @Override
    public LocalDate value8() {
        return getRegisterDate();
    }

    @Override
    public String value9() {
        return getAccountStatus();
    }

    @Override
    public ProfileInfoRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ProfileInfoRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public ProfileInfoRecord value3(String value) {
        setRealName(value);
        return this;
    }

    @Override
    public ProfileInfoRecord value4(String value) {
        setAboutMe(value);
        return this;
    }

    @Override
    public ProfileInfoRecord value5(String value) {
        setProfilePicture(value);
        return this;
    }

    @Override
    public ProfileInfoRecord value6(Short value) {
        setCountryId(value);
        return this;
    }

    @Override
    public ProfileInfoRecord value7(Long value) {
        setRating(value);
        return this;
    }

    @Override
    public ProfileInfoRecord value8(LocalDate value) {
        setRegisterDate(value);
        return this;
    }

    @Override
    public ProfileInfoRecord value9(String value) {
        setAccountStatus(value);
        return this;
    }

    @Override
    public ProfileInfoRecord values(UUID value1, String value2, String value3, String value4, String value5, Short value6, Long value7, LocalDate value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfileInfoRecord
     */
    public ProfileInfoRecord() {
        super(ProfileInfo.PROFILE_INFO_ENTITY);
    }

    /**
     * Create a detached, initialised ProfileInfoRecord
     */
    public ProfileInfoRecord(UUID id, String username, String realName, String aboutMe, String profilePicture, Short countryId, Long rating, LocalDate registerDate, String accountStatus) {
        super(ProfileInfo.PROFILE_INFO_ENTITY);

        setId(id);
        setUsername(username);
        setRealName(realName);
        setAboutMe(aboutMe);
        setProfilePicture(profilePicture);
        setCountryId(countryId);
        setRating(rating);
        setRegisterDate(registerDate);
        setAccountStatus(accountStatus);
    }

    /**
     * Create a detached, initialised ProfileInfoRecord
     */
    public ProfileInfoRecord(ProfileInfoEntity value) {
        super(ProfileInfo.PROFILE_INFO_ENTITY);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setRealName(value.getRealName());
            setAboutMe(value.getAboutMe());
            setProfilePicture(value.getProfilePicture());
            setCountryId(value.getCountryId());
            setRating(value.getRating());
            setRegisterDate(value.getRegisterDate());
            setAccountStatus(value.getAccountStatus());
        }
    }
}
