spring:
  application:
    name: impl

  liquibase:
    enabled: true
    change-log: classpath:/db/database-changelog-master.yml
    url: jdbc:postgresql://localhost:5432/SkillShareDb
    user: postgres
    password: qwerty1234
    driver-class-name: org.postgresql.Driver

  datasource:
    url: jdbc:postgresql://localhost:5432/SkillShareDb
    username: postgres
    password: qwerty1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  freemarker:
    suffix: .ftl

cloudinary:
  cloud_name: debjgvnym
  api_key: 364164765398895
  api_secret: mIIkpEjFGlusCjSM8ccwQM1AjyY

jwt:
  expiration.access.millis: 600000
  secret: Q3rEz8QVq8mV/pcRTV+NRDM7ylWjMRsadnpsZr8tcFUWQooHakzf5KzD48VfEAmcjIAXbSTHv89uSzcC5yAsyw==

rt:
  expiration.access.millis: 2419200000

logging:
  level:
    org:
      springframework: INFO

logger:
  rest-controllers:
    enabled: true
