spring:
  application:
    name: impl
  profiles:
    active: development

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  freemarker:
    suffix: .ftl

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jackson:
    date-format: HH:mm:ss dd-MM-yyyy

cloudinary:
  cloud_name: debjgvnym
  api_key: 364164765398895
  api_secret: mIIkpEjFGlusCjSM8ccwQM1AjyY

jwt:
  expiration.access.millis: 600000
  secret: Q3rEz8QVq8mV/pcRTV+NRDM7ylWjMRsadnpsZr8tcFUWQooHakzf5KzD48VfEAmcjIAXbSTHv89uSzcC5yAsyw==

rt:
  expiration.access.millis: 2419200000

logging:
  level:
    org:
      springframework: INFO

logger:
  rest-controllers:
    enabled: true
  annotations:
    enabled: true
