spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/database-changelog-master.yml
    url: jdbc:postgresql://localhost:5432/SkillShareDb
    user: postgres
    password: qwerty1234
    driver-class-name: org.postgresql.Driver

  datasource:
    url: jdbc:postgresql://localhost:5432/SkillShareDb
    username: postgres
    password: qwerty1234
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ru:
      kpfu:
        itis: DEBUG