/*
 * This file is generated by jOOQ.
 */
package ru.skillaurora.profileservice.model.jooq.schema;


import ru.skillaurora.profileservice.model.jooq.schema.tables.Country;
import ru.skillaurora.profileservice.model.jooq.schema.tables.ProfileInfo;
import ru.skillaurora.profileservice.model.jooq.schema.tables.Skill;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Словарь стран
     */
    public static final Country COUNTRY_ENTITY = Country.COUNTRY_ENTITY;

    /**
     * Таблица данных профиля пользователя
     */
    public static final ProfileInfo PROFILE_INFO_ENTITY = ProfileInfo.PROFILE_INFO_ENTITY;

    /**
     * Таблица навыков пользователя
     */
    public static final Skill SKILL_ENTITY = Skill.SKILL_ENTITY;
}
