/*
 * This file is generated by jOOQ.
 */
package ru.skillaurora.profileservice.model.jooq.schema.tables.pojos;


import java.io.Serializable;


/**
 * Словарь стран
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Short id;
    private String code;
    private String name;

    public CountryEntity() {}

    public CountryEntity(CountryEntity value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
    }

    public CountryEntity(
        Short id,
        String code,
        String name
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
    }

    /**
     * Getter for <code>public.country.id</code>.
     */
    public Short getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.country.id</code>.
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.country.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>public.country.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>public.country.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.country.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CountryEntity other = (CountryEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CountryEntity (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
