/*
 * This file is generated by jOOQ.
 */
package ru.skillaurora.profileservice.model.jooq.schema.tables.pojos;


import ru.skillaurora.profileservice.dto.response.SkillResponse;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;


/**
 * Таблица данных профиля пользователя
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileInfoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String username;
    private String realName;
    private String aboutMe;
    private String profilePicture;
    private Short countryId;
    private Long rating;
    private LocalDate registerDate;
    private String accountStatus;

    private CountryEntity country;
    private List<SkillResponse> skills;

    public ProfileInfoEntity() {}

    public ProfileInfoEntity(ProfileInfoEntity value) {
        this.id = value.id;
        this.username = value.username;
        this.realName = value.realName;
        this.aboutMe = value.aboutMe;
        this.profilePicture = value.profilePicture;
        this.countryId = value.countryId;
        this.rating = value.rating;
        this.registerDate = value.registerDate;
        this.accountStatus = value.accountStatus;
    }

    public ProfileInfoEntity(
        UUID id,
        String username,
        String realName,
        String aboutMe,
        String profilePicture,
        Short countryId,
        Long rating,
        LocalDate registerDate,
        String accountStatus
    ) {
        this.id = id;
        this.username = username;
        this.realName = realName;
        this.aboutMe = aboutMe;
        this.profilePicture = profilePicture;
        this.countryId = countryId;
        this.rating = rating;
        this.registerDate = registerDate;
        this.accountStatus = accountStatus;
    }

    /**
     * Getter for <code>public.profile_info.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.profile_info.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.profile_info.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.profile_info.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>public.profile_info.real_name</code>.
     */
    public String getRealName() {
        return this.realName;
    }

    /**
     * Setter for <code>public.profile_info.real_name</code>.
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * Getter for <code>public.profile_info.about_me</code>.
     */
    public String getAboutMe() {
        return this.aboutMe;
    }

    /**
     * Setter for <code>public.profile_info.about_me</code>.
     */
    public void setAboutMe(String aboutMe) {
        this.aboutMe = aboutMe;
    }

    /**
     * Getter for <code>public.profile_info.profile_picture</code>.
     */
    public String getProfilePicture() {
        return this.profilePicture;
    }

    /**
     * Setter for <code>public.profile_info.profile_picture</code>.
     */
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    /**
     * Getter for <code>public.profile_info.country_id</code>.
     */
    public Short getCountryId() {
        return this.countryId;
    }

    /**
     * Setter for <code>public.profile_info.country_id</code>.
     */
    public void setCountryId(Short countryId) {
        this.countryId = countryId;
    }

    /**
     * Getter for <code>public.profile_info.rating</code>.
     */
    public Long getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>public.profile_info.rating</code>.
     */
    public void setRating(Long rating) {
        this.rating = rating;
    }

    /**
     * Getter for <code>public.profile_info.register_date</code>.
     */
    public LocalDate getRegisterDate() {
        return this.registerDate;
    }

    /**
     * Setter for <code>public.profile_info.register_date</code>.
     */
    public void setRegisterDate(LocalDate registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * Getter for <code>public.profile_info.account_status</code>.
     */
    public String getAccountStatus() {
        return this.accountStatus;
    }

    /**
     * Setter for <code>public.profile_info.account_status</code>.
     */
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }

    public CountryEntity getCountry() {
        return country;
    }

    public void setCountry(CountryEntity country) {
        this.country = country;
    }

    public List<SkillResponse> getSkills() {
        return skills;
    }

    public void setSkills(List<SkillResponse> skills) {
        this.skills = skills;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProfileInfoEntity other = (ProfileInfoEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.realName == null) {
            if (other.realName != null)
                return false;
        }
        else if (!this.realName.equals(other.realName))
            return false;
        if (this.aboutMe == null) {
            if (other.aboutMe != null)
                return false;
        }
        else if (!this.aboutMe.equals(other.aboutMe))
            return false;
        if (this.profilePicture == null) {
            if (other.profilePicture != null)
                return false;
        }
        else if (!this.profilePicture.equals(other.profilePicture))
            return false;
        if (this.countryId == null) {
            if (other.countryId != null)
                return false;
        }
        else if (!this.countryId.equals(other.countryId))
            return false;
        if (this.rating == null) {
            if (other.rating != null)
                return false;
        }
        else if (!this.rating.equals(other.rating))
            return false;
        if (this.registerDate == null) {
            if (other.registerDate != null)
                return false;
        }
        else if (!this.registerDate.equals(other.registerDate))
            return false;
        if (this.accountStatus == null) {
            if (other.accountStatus != null)
                return false;
        }
        else if (!this.accountStatus.equals(other.accountStatus))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.realName == null) ? 0 : this.realName.hashCode());
        result = prime * result + ((this.aboutMe == null) ? 0 : this.aboutMe.hashCode());
        result = prime * result + ((this.profilePicture == null) ? 0 : this.profilePicture.hashCode());
        result = prime * result + ((this.countryId == null) ? 0 : this.countryId.hashCode());
        result = prime * result + ((this.rating == null) ? 0 : this.rating.hashCode());
        result = prime * result + ((this.registerDate == null) ? 0 : this.registerDate.hashCode());
        result = prime * result + ((this.accountStatus == null) ? 0 : this.accountStatus.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProfileInfoEntity (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(realName);
        sb.append(", ").append(aboutMe);
        sb.append(", ").append(profilePicture);
        sb.append(", ").append(countryId);
        sb.append(", ").append(rating);
        sb.append(", ").append(registerDate);
        sb.append(", ").append(accountStatus);

        sb.append(")");
        return sb.toString();
    }
}
