/*
 * This file is generated by jOOQ.
 */
package ru.skillaurora.profileservice.model.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * Таблица навыков пользователя
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SkillEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID userId;
    private Long tagId;

    public SkillEntity() {}

    public SkillEntity(SkillEntity value) {
        this.userId = value.userId;
        this.tagId = value.tagId;
    }

    public SkillEntity(
        UUID userId,
        Long tagId
    ) {
        this.userId = userId;
        this.tagId = tagId;
    }

    /**
     * Getter for <code>public.skill.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.skill.user_id</code>.
     */
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.skill.tag_id</code>.
     */
    public Long getTagId() {
        return this.tagId;
    }

    /**
     * Setter for <code>public.skill.tag_id</code>.
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SkillEntity other = (SkillEntity) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!this.tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.tagId == null) ? 0 : this.tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SkillEntity (");

        sb.append(userId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
